# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-21 02:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=50)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('genre_id', models.IntegerField(default=0)),
                ('poster_path', models.CharField(max_length=100)),
                ('overview', models.TextField(max_length=5000)),
            ],
        ),
    ]
