# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-21 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0002_searchmovies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='date',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='movies',
            name='genre_id',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='movie_id',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='overview',
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='movies',
            name='poster_path',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='movies',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='searchmovies',
            name='date',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='searchmovies',
            name='genre_id',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='searchmovies',
            name='movie_id',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='searchmovies',
            name='overview',
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='searchmovies',
            name='poster_path',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='searchmovies',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='searchmovies',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
