# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-21 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0003_auto_20160821_0317'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendMovies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.IntegerField(blank=True, default=0, null=True)),
                ('title', models.CharField(blank=True, max_length=50)),
                ('date', models.CharField(blank=True, max_length=50)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('genre_id', models.IntegerField(blank=True, default=0, null=True)),
                ('poster_path', models.CharField(blank=True, max_length=100)),
                ('overview', models.TextField(blank=True, max_length=5000)),
            ],
        ),
        migrations.AlterField(
            model_name='movies',
            name='genre_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='movie_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
